### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sandruskyi** [sandruskyi/SUMO_DEMOS#1]
- [ ] https://sumo.dlr.de/docs/Models/Emissions.html

- [ ] https://sumo.dlr.de/docs/Simulation/Output/EmissionOutput.html

- [ ] https://sumo.dlr.de/docs/netedit.html#additional_elements
